# Generated by Django 4.2.1 on 2023-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="private",
            field=models.IntegerField(default=1),
        ),
    ]
