# Generated by Django 4.2.1 on 2023-05-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="private",
        ),
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PRIVATE",
                max_length=10,
            ),
        ),
    ]
