# Generated by Django 4.2.3 on 2023-07-22 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 22, 0, 30, 5, 670169)
                    ),
                ),
                ("track", models.TextField(default="")),
                ("artist", models.TextField(default="")),
                ("time", models.IntegerField(default=0)),
            ],
        ),
    ]
