# Generated by Django 4.2.3 on 2023-07-22 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.TextField(default="No Album"),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.TextField(default="No Artist"),
        ),
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 22, 0, 35, 14, 140797)
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="track",
            field=models.TextField(default="No Track"),
        ),
    ]
