# Generated by Django 4.2.3 on 2023-07-22 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0003_alter_song_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 22, 0, 44, 59, 662952)
            ),
        ),
    ]
