# Generated by Django 4.2.3 on 2023-07-23 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0004_alter_song_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistStats",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("artist", models.TextField(default="No Artist")),
                ("plays", models.IntegerField(default=0)),
                (
                    "totaltime",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 22, 23, 53, 26, 763719)
            ),
        ),
    ]
