# Generated by Django 4.2.3 on 2023-07-23 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0006_rename_artiststats_artiststat_alter_song_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumStat",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("album", models.TextField(default="No Album")),
                ("plays", models.IntegerField(default=0)),
                (
                    "total_time",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackStat",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("track", models.TextField(default="No Track")),
                ("plays", models.IntegerField(default=0)),
                (
                    "total_time",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="artiststat",
            old_name="totaltime",
            new_name="total_time",
        ),
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 23, 1, 18, 38, 672183)
            ),
        ),
    ]
