# Generated by Django 4.2.3 on 2023-07-23 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0007_albumstat_trackstat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 23, 1, 18, 44, 831756)
            ),
        ),
    ]
