# Generated by Django 4.2.1 on 2023-05-28 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 28, 0, 48, 6, 657732))),
                ('author', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
