# Generated by Django 4.2.1 on 2023-05-28 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.IntegerField(default=-1)),
                ('user', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 3, 3, 4, 633362)),
        ),
    ]
