# Generated by Django 4.2.1 on 2023-05-28 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.IntegerField(default=-1)),
                ('user', models.TextField(default='')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 15, 0, 58, 129555)),
        ),
    ]
