# Generated by Django 4.2.1 on 2023-05-29 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 22, 40, 21, 30783)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 22, 40, 21, 29783)),
        ),
    ]
