# Generated by Django 4.2.1 on 2023-05-31 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_alter_comment_date_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 48, 42, 514347)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 48, 42, 513348)),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('since', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 12, 48, 42, 514347))),
                ('friends_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
