# Generated by Django 4.2.1 on 2023-06-01 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_comment_date_alter_friend_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 20, 15, 30, 878373)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='since',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 20, 15, 30, 878373)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 20, 15, 30, 879373)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 20, 15, 30, 878373)),
        ),
    ]
